### ISSUE TITLE
Filter by date is not working

### ISSUE THREAD

**Issue by bradyk** [DevProgress/nomad2016#14]
Clicking on the dropdown doesn't filter the map by date as I was expecting. It is filtering on something, but not correctly...

I have a hunch that it is filtering on the date created for the ride record. But I can't figure it out for sure.

I don't know what is going on, but if someone could figure it out it'd be great! (I did futz around with the css for that button over the weekend.)

![screen shot 2016-10-18 at 1 30 06 pm](https://cloud.githubusercontent.com/assets/1565834/19495687/416c3872-9539-11e6-8308-41cdb4ed4bc4.png)

**Comment by TheRealBenJones** [comment]
Looks like there is a bunch of bad data in the DB (No start location). I'll throw together a fix.

**Comment by TheRealBenJones** [comment]
https://github.com/DevProgress/nomad2016/pull/15

**Comment by wboykinm** [comment]
@BCJonesey nailed it.
