### ISSUE TITLE
Map pins not clickable on mobile

### ISSUE THREAD

**Issue by wboykinm** [DevProgress/nomad2016#4]
. . . in their load state. The infowindows **do** pop up once a location and date have been selected.

**Comment by wboykinm** [comment]
Note I can't really replicate this in the chrome debugger w/ mobile dimension set. I've only seen it in an actual mobile browser.

**Comment by flibbertigibbet** [comment]
Haven't been able to replicate via network throttling. I did notice that it is necessary to tap/click the pin anchor point, rather than the pin itself.

**Comment by wboykinm** [comment]
Hopefully limited to android edge cases. Closing until corroborated.
